version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=prest
      - POSTGRES_DB=prest
      - POSTGRES_PASSWORD=prest
    volumes:
      - './data/heroes.csv:/heroes.csv'
  prest:
    image: prest/prest
    container_name: prest
    network_mode: bridge
    volumes:
      - './prest.toml:/app/prest.toml'
    ports:
      - '8005:3000'