debug=true

[pg]
url="postgres://prest:prest@host.docker.internal:5432/prest"

[ssl]
mode="disable"

[cors]
alloworigin=["*"]
allowheaders=["Content-Type","authorization"]
allowmethods=["GET","DELETE","POST","PUT","PATCH","OPTIONS"]
